---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: newcluster1
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 4

cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["audit", "authenticator", "controllerManager"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"
