apiVersion: v1
kind: Pod
metadata:
  name: webserver2
  labels:
    app: app1
spec:
  containers:
    - name: web
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
