apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: app1-web
  labels:
    env: app1-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      env: app1-frontend
  template:
    metadata:
      labels:
        env: app1-frontend
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: svc-app1-frontend
spec:
  selector:
    env: app1-frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---